// Terrible loader for Ethereum v3 keystores, as generated by MyEtherWallet.
// Created because both ethsign and OpenEthereum are GPLv3
// and nft_ptr is ostensibly a library that others can integrate

use secp256k1::SecretKey;

// Loads an account and its associated SecretKey from a keystore.
// Warning: this is not secure; do NOT ever load a wallet containing real money using this!!
pub fn load_keystore_from_string(input: &str, password: &str) -> Result<SecretKey, ()> {
    panic!("Unimplemented");
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let key =
            load_keystore_from_string(include_str!("SampleKeystore.keystore"), "sample password")
                .unwrap();
        assert_eq!(2 + 2, 4);
    }
}
